export const AVAILABLE_SERVERS = [
  {
    id: 'SRV-001',
    name: 'web-server-01',
    type: 'Web',
    ip: '10.0.1.1',
    os: 'Ubuntu 22.04',
    status: 'available',
    region: '서울',
    cpu: 4,
    memory: 16,
    storage: 100,
  },
  {
    id: 'SRV-002',
    name: 'web-server-02',
    type: 'Web',
    ip: '10.0.1.2',
    os: 'Ubuntu 22.04',
    status: 'available',
    region: '서울',
    cpu: 4,
    memory: 16,
    storage: 100,
  },
  {
    id: 'SRV-003',
    name: 'db-master-01',
    type: 'Database',
    ip: '10.0.2.1',
    os: 'CentOS 8',
    status: 'available',
    region: '서울',
    cpu: 8,
    memory: 64,
    storage: 500,
  },
  {
    id: 'SRV-004',
    name: 'db-replica-01',
    type: 'Database',
    ip: '10.0.2.2',
    os: 'CentOS 8',
    status: 'available',
    region: '부산',
    cpu: 8,
    memory: 64,
    storage: 500,
  },
  {
    id: 'SRV-005',
    name: 'cache-node-01',
    type: 'Cache',
    ip: '10.0.3.1',
    os: 'Amazon Linux 2',
    status: 'available',
    region: '서울',
    cpu: 2,
    memory: 8,
    storage: 50,
  },
  {
    id: 'SRV-006',
    name: 'ml-gpu-01',
    type: 'ML',
    ip: '10.0.4.1',
    os: 'Ubuntu 20.04',
    status: 'available',
    region: '서울',
    cpu: 16,
    memory: 128,
    storage: 1000,
  },
  {
    id: 'SRV-007',
    name: 'ml-gpu-02',
    type: 'ML',
    ip: '10.0.4.2',
    os: 'Ubuntu 20.04',
    status: 'maintenance',
    region: '부산',
    cpu: 16,
    memory: 128,
    storage: 1000,
  },
  {
    id: 'SRV-008',
    name: 'api-gateway-01',
    type: 'Gateway',
    ip: '10.0.5.1',
    os: 'Ubuntu 22.04',
    status: 'available',
    region: '서울',
    cpu: 4,
    memory: 32,
    storage: 200,
  },
  {
    id: 'SRV-009',
    name: 'log-collector-01',
    type: 'Logging',
    ip: '10.0.6.1',
    os: 'Debian 11',
    status: 'available',
    region: '서울',
    cpu: 2,
    memory: 16,
    storage: 2000,
  },
  {
    id: 'SRV-010',
    name: 'monitor-01',
    type: 'Monitoring',
    ip: '10.0.7.1',
    os: 'Ubuntu 22.04',
    status: 'available',
    region: '부산',
    cpu: 2,
    memory: 8,
    storage: 100,
  },
];

export const PROJECTS = [
  { id: 'PRJ-001', name: '이커머스 플랫폼' },
  { id: 'PRJ-002', name: '사내 데이터 분석 시스템' },
  { id: 'PRJ-003', name: 'AI 추천 서비스' },
  { id: 'PRJ-004', name: '고객 지원 포털' },
];

export const TYPE_COLORS = {
  Web: '#1890ff',
  Database: '#52c41a',
  Cache: '#fa8c16',
  ML: '#722ed1',
  Gateway: '#13c2c2',
  Logging: '#eb2f96',
  Monitoring: '#faad14',
};
