export const SOURCE_ACCOUNT = {
  id: 'ACC-001',
  name: '팀 Alpha',
  totalCpu: 64,
  totalGpu: 16,
  totalMemory: 512,
  usedCpu: 32,
  usedGpu: 12,
  usedMemory: 248,
};

export const TARGET_ACCOUNTS = [
  {
    id: 'ACC-002',
    name: '팀 Beta',
    totalCpu: 32,
    totalGpu: 8,
    totalMemory: 256,
    usedCpu: 20,
    usedGpu: 2,
    usedMemory: 80,
  },
  {
    id: 'ACC-003',
    name: '팀 Gamma',
    totalCpu: 16,
    totalGpu: 4,
    totalMemory: 128,
    usedCpu: 14,
    usedGpu: 3,
    usedMemory: 100,
  },
  {
    id: 'ACC-004',
    name: '팀 Delta',
    totalCpu: 48,
    totalGpu: 12,
    totalMemory: 384,
    usedCpu: 8,
    usedGpu: 0,
    usedMemory: 64,
  },
];

export const RESOURCES = [
  {
    id: 'RES-001',
    name: 'Web Server Alpha',
    cpu: 4,
    gpu: 0,
    memory: 16,
    startDate: '2023-01-15',
    usageDays: 365,
    status: 'running',
  },
  {
    id: 'RES-002',
    name: 'ML Training Node',
    cpu: 8,
    gpu: 4,
    memory: 64,
    startDate: '2023-07-01',
    usageDays: 180,
    status: 'running',
  },
  {
    id: 'RES-003',
    name: 'DB Replica Server',
    cpu: 2,
    gpu: 0,
    memory: 32,
    startDate: '2023-10-01',
    usageDays: 90,
    status: 'running',
  },
  {
    id: 'RES-004',
    name: 'Cache Node',
    cpu: 2,
    gpu: 0,
    memory: 8,
    startDate: '2023-12-01',
    usageDays: 45,
    status: 'stopped',
  },
  {
    id: 'RES-005',
    name: 'GPU Compute Node',
    cpu: 16,
    gpu: 8,
    memory: 128,
    startDate: '2024-01-01',
    usageDays: 30,
    status: 'running',
  },
];
